ValueSet:    GeneticTestVS
Title: "Genetic Test Value Set"
Description: "Value set containing codes representing genetic tests. Currently the best source of codes is the [Genetic Test Registry](http://www.ncbi.nlm.nih.gov/gtr). The user should be aware that the GTR cannot be a sole reliable source since the test data is voluntarily updated and there is no overarching data steward. This value set contains all codes from http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes (namely, the subset of LOINC codes with CLASSTYPE = 1), plus all codes in GTR.

Implementation note: Although only a subset of LOINC codes is formally part of this value set, the value set itself contains all codes in LOINC, because FHIR cannot create an implicitly-defined value set based on LOINC's CLASSTYPE property.

Conformance note: To be conformant to US Core, a LOINC code must be used, if available. Only if there is no suitable code in LOINC may other codes (such as those from GTR) be used."
* codes from system LNC // where CLASSTYPE = 1 (FHIR terminology server can't handle this yet)
* codes from system GTR

ValueSet:    ClinVarVS
Title: "ClinVar Value Set"
Description: "Value set of human genetic variants, drawn from [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/). The codes in this value set refer to the ClinVar Variation ID, or the identifier for the variant or set of variants that were interpreted. [Source: NCBI ClinVar Data Dictionary](https://www.ncbi.nlm.nih.gov/projects/clinvar/ClinVarDataDictionary.pdf)"
* codes from system CLINVAR

ValueSet:     CancerBodyLocationVS
Title: "Cancer Body Location Value Set"
Description:  "Codes describing the location(s) of primary or secondary cancer. The value set includes all codes from the SNOMED CT body structure hierarchy (codes descending from 123037004 'Body Structure'). The cancer body location may also be expressed using ICD-O-3 topography codes, however, those codes are not included here due to intellectual property restrictions. No other code systems are considered conformant."
* codes from system SCT where code is-a SCT#123037004  "Body Structure"

ValueSet:   HistologyMorphologyBehaviorVS
Title: "Histology Morphology Behavior Value Set"
Description: "Codes representing the structure, arrangement, and behavioral characteristics of malignant neoplasms, and cancer cells. Inclusion criteria: in situ neoplasms and malignant neoplasms. Exclusion criteria: benign neoplasms and neoplasms of unspecified behavior. Note: As the vocabulary binding is extensible within this IG, ICD-O-3 morphology codes (including behavior suffix) may also be used; they are not included in the value set for intellectual property reasons. For primary cancers, the ICD-O-3 behavior suffix should be /1, /2, or /3. For secondary cancers, the ICD-O-3 behavior suffix should be /6. Only SNOMED CT and ICD-O-3 are considered conformant to the specification. However, to be compliant with US Core Profiles, ICD-O-3 may only be used if there is no suitable code in SNOMED CT."
* codes from system SCT where code is-a SCT#367651003 "Malignant neoplasm of primary, secondary, or uncertain origin (morphologic abnormality)" 
* codes from system SCT where code is-a SCT#399919001 "Carcinoma in situ - category (morphologic abnormality)"
* codes from system SCT where 
    code is-a SCT#399983006 "In situ adenomatous neoplasm - category (morphologic abnormality)" and
    code is-not-a SCT#399983006 "Papillary neoplasm, pancreatobiliary-type, with high grade intraepithelial neoplasia (morphologic abnormality)" and
    code is-not-a SCT#128640002 "Glandular intraepithelial neoplasia, grade III (morphologic abnormality)" and
    code is-not-a SCT#450890000 "Glandular intraepithelial neoplasia, low grade (morphologic abnormality)" and
    code is-not-a SCT#703548001 "Endometrioid intraepithelial neoplasia (morphologic abnormality)"
* SCT#399878004 "Malignant neoplasm with pilar differentiation (morphologic abnormality)"

ValueSet:   CancerHistologicGradeVS
Title:  "Cancer Histologic Grade Value Set"
Description:  "The grade of the tumor. This is a subset of the LOINC answer list LL213-0, which represents allowable values for NAACCR data item #440. The original answer list is outdated, as it includes terms pointing to the lineage of hematopoietic/lymphoid neoplasms, which have been retired by NAACCR as of version 18 Data Standards and Data Dictionary."
* SCT#54102005  "G1 grade (finding)"
* SCT#1663004   "G2 grade (finding)"
* SCT#61026006  "G3 grade (finding)"
* SCT#258245003 "G4 grade (finding)"
* SCT#60815008  "Grade not determined (finding)" // synonyms include not applicable, not stated
//SCT#12619005  "GX grade (finding)" // includes synonym "Grade cannot be assessed", this is the terminology used by AJCC

ValueSet: SurgicalMarginInvolvementVS
Title: "Surgical Margin Involvement Value Set"
Description:  "Indication of whether the tumor was involved at the edge of resection."
* SCT#55182004 "Surgical margin uninvolved by tumor (finding)"
* SCT#370109009 "Surgical margin involved by tumor (finding)"

ValueSet: CancerDiseaseStatusEvidenceTypeVS
Title: "Cancer Disease Status Evidence Type Value Set"
Description:  "The type of evidence backing up the clinical determination of cancer progression. The code 'SCT#252416005 Histopathology test (procedure)' is intended to be used when there is a biopsy that contributes evidence of the cancer disease status."
//SCT codes are children of SCT#386053000 "Evaluation procedure (procedure)"
* SCT#363679005 "Imaging (procedure)"
* SCT#252416005 "Histopathology test (procedure)"
* SCT#711015009 "Assessment of symptom control (procedure)"
* SCT#5880005   "Physical examination procedure (procedure)"
* SCT#250724005 "Tumor marker measurement (procedure)"
* SCT#386344002 "Laboratory data interpretation (procedure)"
//MTH#C0005516	"Biological markers"

ValueSet:   CancerStagingSystemVS 
Title: "Cancer Staging System Value Set"
Description:    "System used for staging. Because SNOMED CT does not currently have a code representing AJCC Version 8, specify the exact text 'AJCC Version 8' in the text sub-field of the code structure, and omit the code."
* SCT#444256004 "American Joint Commission on Cancer, Cancer Staging Manual, 6th edition neoplasm staging system (tumor staging)"
* SCT#443830009 "American Joint Commission on Cancer, Cancer Staging Manual, 7th edition neoplasm staging system (tumor staging)"
* SCT#258235000 "International Union Against Cancer (tumor staging)"

ValueSet: TNMStageGroupVS
Title: "TNM Stage Group Value Set"
Description: "This value set is intended to contain allowable values for Stage Group, according to TNM staging rules. SNOMED CT codes or AJCC codes (preferrably, version 8 for current cancers) are allowed, but are not listed here due to AJCC intellectual property restrictions.

*AJCC terminology: examples of stage groups include 'Stage 0' and 'Stage IIA'. The full set of stage groups, as well rules on how to assign a stage group, can be accessed through the AJCC Staging Manual and any applicable updates and corrections, as well as the AJCC API.

* SNOMED CT has content representing stage group under the hierarchy of 261612004 'Stages', such as 258215001 'Stage 1' and 261614003 'Stage2A'. In addition, SNOMED CT may not have complete TNM staging terminology and may require supplementation with codes from another controlled vocabulary (e.g. NCI Thesaurus)."
* codes from system AJCC

ValueSet: TNMPrimaryTumorCategoryVS
Title: "TNM Primary Tumor Category Value Set"
Description: "This value set is intended to contain allowable values for the T category, according to TNM staging rules. SNOMED CT codes or AJCC codes (preferrably, version 8 for current cancers) are allowed, but are not listed here due to AJCC intellectual property restrictions.

* AJCC terminology: examples of T categories include 'cTX', used when the tumor primary tumor cannot be evaluated, 'pT0', denoting there is no evidence of a primary tumor, and 'pTis', referencing carcinoma in situ (with some cancer-specific exceptions). Other T categories refer to increasing size of the primary tumor. Please note allowable T categories may vary between clinical and pathologic classifications. The full set of allowable clinical and pathologic T categories, along with its current descriptions, can be accessed through the AJCC Staging Manual and any applicable updates and corrections, as well as the AJCC API.

* SNOMED CT has content related to the T category under the hierarchy of 385356007 'Tumor stage finding', such as 23351008 'T1 category' and 261650005 'Tumor stage T1c'. If using SNOMED CT to store T category findings, the use of codes that do not contain descriptions of the categories, such as the examples provided, is encouraged, as stage finding codes in SNOMED CT may not be up-to-date with current AJCC guidance. Note that SNOMED CT codes do not always make a distinction between clinical and pathological classifications (e.g. cT1 and pT1 may be represented by the same SNOMED CT code 23351008 'T1 category'). In addition, SNOMED CT may not have complete TNM staging terminology and may require supplementation with codes from another controlled vocabulary (e.g. NCI Thesaurus)."
* codes from system AJCC

ValueSet: TNMRegionalNodesCategoryVS
Title: "TNM Regional Nodes Category Value Set"
Description: "This value set is intended to contain allowable values for the N category, according to TNM staging rules. SNOMED CT codes or AJCC codes (preferrably, version 8 for current cancers) are allowed, but are not listed here due to AJCC intellectual property restrictions.

* AJCC terminology: examples of N categories include 'cN0', indicating no evidence of lymph node involvement, and 'pN1', indicating regional lymph node involvement to a small extent, with specific thresholds for the lymph node groups and number of lymph nodes involved. Other N categories refer to increasing lymph node involvement. Please note allowable N categories may vary between clinical and pathologic classifications. The full set of allowable clinical and pathologic N categories, along with its current descriptions, can be accessed through the AJCC Staging Manual and any applicable updates and corrections, as well as the AJCC API.

* SNOMED CT has content related to the N category under the hierarchy of 385382003 'Node category finding', such as 5856006 'N3 category' and 277672002 'Node stage N1a'. If using SNOMED CT to store N category findings, the use of codes that do not contain descriptions of the categories, such as the examples provided, is encouraged, as stage finding codes in SNOMED CT may not be up-to-date with current AJCC guidance. Note that SNOMED CT codes do not always make a distinction between clinical and pathological classifications (e.g. 'cN1' and 'pN1' may be represented by the same SNOMED CT code 53623008 'N1 category'). In addition, SNOMED CT may not have complete TNM staging terminology and may require supplementation with codes from another controlled vocabulary (e.g. NCI Thesaurus)."
* codes from system AJCC

ValueSet: TNMDistantMetastasesCategoryVS
Title: "TNM Distant Metastases Category Value Set"
Description: "This value set is intended to contain allowable values for the M category, according to TNM staging rules. SNOMED CT codes or AJCC codes (preferrably, version 8 for current cancers) are allowed, but are not listed here due to AJCC intellectual property restrictions.

* AJCC terminology: examples of M categories include 'cM0', denoting there is no evidence of distant metastases, and 'pM1', an indication that the cancer has metasticized. The full set of allowable clinical and pathologic M categories, along with its current descriptions, can be accessed through the AJCC Staging Manual and any applicable updates and corrections, as well as the AJCC API.

* SNOMED CT: The SNOMED CT US Edition has content related to the M category under the hierarchy of 385380006 'Metastasis category finding', such as 30893008 'M0 category' and 443841006 'pM1a category'. If using SNOMED CT to store M category findings, the use of codes that do not contain descriptions of the categories, such as the examples provided, is encouraged, as stage finding codes in SNOMED CT may not be up-to-date with current AJCC guidance. Note that SNOMED CT codes do not always make a distinction between clinical and pathological classifications (e.g. 'cM0' and 'pM0' may be represented by the same SNOMED CT code 30893008 'M0 category'). In addition, SNOMED CT may not have complete TNM staging terminology and may require supplementation with codes from another controlled vocabulary (e.g. NCI Thesaurus)."
* codes from system AJCC


ValueSet: CancerRelatedSurgicalProcedureVS
Title: "Cancer Related Surgical Procedure Value Set"
Description: "Includes selected SNOMED CT codes that may be used in the treatment of cancer tumors. Codes from ICD-10-PCS and CPT are acceptable. CPT codes are not listed here due to intellectual property restrictions. ICD-10-PCS codes are not listed because of a limitation in the FHIR Implementation Guide publisher. For CPT and ICD-10-PCS, only codes representing surgical procedures should be used. 

Conformance note: If an ICD-10-PCS code is used, and a semantically equivalent SNOMED CT code is available, the resulting FHIR Procedure instance will not be compliant with [US Core Profiles](http://hl7.org/fhir/us/core/STU3/index.html)."
* SCT#174337000    "Destruction of lesion"
* SCT#49264007    "Excision of lesion"
* SCT#119894003    "Anus excision"
* SCT#24265000    "Operation on anus [NOS]"
* SCT#48185007    "Destruction of lesion"
* SCT#108034003    "Excision of lesion"
* SCT#112902005    "Partial cystectomy"
* SCT#63016009    "Total Cystectomy"
* SCT#64063003    "Radical Cystectomy"
* SCT#287716007    "Urinary bladder reconstruction"
* SCT#52224004    "Pelvic exenteration"
* SCT#149649000    "Cystectomy dome of bladder"
* SCT#14861000    "Operation on bladder [NOS]"
* SCT#18734000    "Destruction of lesion"
* SCT#68471001    "Excision of lesion"
* SCT#112705001    "Amputation"
* SCT#57168000    "Operation on bone [NOS]"
* SCT#68829005    "Destruction of lesion"
* SCT#64368001    "Partial mastectomy"
* SCT#70183006    "Subcutaneous mastectomy"
* SCT#172043006    "Total mastectomy"
* SCT#406505007    "Modified radical mastectomy"
* SCT#384723003    "Radical mastectomy"
* SCT#359740003    "Extended radical mastectomy"
* SCT#69031006    "Mastectomy"
* SCT#392090004    "Operation on breast [NOS]"
* SCT#31197001    "Destruction of lesion"
* SCT#36384005    "Excision of lesion"
* SCT#116140006    "Total hysterctomy"
* SCT#236886002    "Hysterectomy"
* SCT#116142003    "Radical hysterectomy"
* SCT#406044008    "Pelvic exentration "
* SCT#112916000    "Operation on cervix [NOS]"
* SCT#176871003    "Destruction of lesion"
* SCT#236884004    "Excision of lesion"
* SCT#387643005    "Partial hysterectomy"
* SCT#116140006    "Total hysterctomy"
* SCT#116142003    "Radical hysterectomy"
* SCT#236886002    "Hysterectomy"
* SCT#406044008    "Pelvic exentration "
* SCT#79876008    "Operation on uterus  [NOS]"
* SCT#18243008    "Destruction of lesion"
* SCT#386553005    "Excision of lesion"
* SCT#3980006    "Partial esophagectomy"
* SCT#14072009    "Total esophagectomy"
* SCT#76443003    "Total esophagectomy with gastropharyngostomy"
* SCT#45900003    "Esophagectomy"
* SCT#48114000    "Operation on esophagus [NOS]"
* SCT#52785004    "Destruction of lesion"
* SCT#69762004    "Excision of lesion"
* SCT#81516001    "Partial nephrectomy"
* SCT#175905003    "Total nephrectomy"
* SCT#116033007    "Radical nephrectomy"
* SCT#175898006    "Kidney operation  [NOS]"
* SCT#78923006    "Destruction of lesion"
* SCT#88623004    "Excision of lesion"
* SCT#80513001    "Partial laryngectomy"
* SCT#66478002    "Total laryngectomy"
* SCT#60041003    "Laryngopharyngectomy"
* SCT#72791001    "Laryngectomy"
* SCT#387636004    "Operation on larynx [NOS]"
* SCT#5415002    "Destruction of lesion"
* SCT#174431000    "Wedge resecton of liver"
* SCT#85946004    "Lobectomy of liver"
* SCT#15257006    "Lobectomy w/ partial excision of adjacent lobes"
* SCT#107963000    "Hepatectomy"
* SCT#13580001000004101   "Excision of tumor of liver"
* SCT#27280000    "Liver transplant w/recipient hepatectomy"
* SCT#4974007    "Operation on liver [NOS]"
* SCT#450608000    "Destruction of lesion"
* SCT#119746007    "Excision of lesion"
* SCT#173170008    "Bilobectomy of lung"
* SCT#359623004    "Total lobectomy of lung"
* SCT#49795001    "Total pneumonectomy"
* SCT#91596000    "Complete excision of lung with mediastinal dissection"
* SCT#119746007    "Operation on lung [NOS]"
* SCT#230859007    "Destruction of lesion"
* SCT#230810008    "Excision of lesion"
* SCT#446103006    "Partial excision of lesion of brain "
* SCT#17537007    "Resection of spinal cord"
* SCT#447115003    "Total excision of lesion of brain"
* SCT#67402009    "Partial lobectomy"
* SCT#171443003    "Total lobectomy"
* SCT#70586009    "Operation on brain [NOS]"
* SCT#177018009    "Destruction of lesion"
* SCT#35887003    "Excision of lesion"
* SCT#116028008    "Salpingo-oophorectomy"
* SCT#29827000    "Bilateral salpingectomy w/oophorectomy"
* SCT#78698008    "Unilateral salpingo-oophorectomy"
* SCT#446526009    "Debulking of neoplasm of ovary"
* SCT#55853002    "Pelvic exenteraion, female"
* SCT#64887002    "Operation on ovary [NOS]"
* SCT#414158004    "Destruction of lesion"
* SCT#287847009    "Partial pancreatectomy"
* SCT#69036001    "Total pancreaticoduodenectomy"
* SCT#9524002    "Total pancreatectomy"
* SCT#265459006    "Total pancreaticodudoenectomy with distal gastrectomy"
* SCT#33149006    "Pancreatectomy"
* SCT#29630005    "Operation on pancreas [NOS]"
* SCT#10522005    "Destruction of lesion"
* SCT#37804007    "Excision of lesion"
* SCT#81870009    "Parotidectomy"
* SCT#11150009    "Partial parotidectomy"
* SCT#13358001    "Total parotidectomy"
* SCT#173486005    "Radical parotidectomy"
* SCT#58456002    "Operation on parotid gland [NOS]"
* SCT#107923001    "Destruction of lesion"
* SCT#3786007    "Excision of lesion"
* SCT#51265002    "Pharyngectomy"
* SCT#232546000    "Total pharyngolaryngectomy w/ laryngectomy"
* SCT#303621003    "Total pharyngectomy"
* SCT#23136006    "Operation on pharynx [NOS]"
* SCT#450514003    "Destruction of lesion"
* SCT#90199006    "Transurethral prostactomy"
* SCT#30426000    "Subtotal prostactomy"
* SCT#26294005    "Radical prostatectomy "
* SCT#65111004    "Pelvic exenteration"
* SCT#90470006    "Prostactomy"
* SCT#741007    "Operation on prostate [NOS]"
* SCT#177975003    "Destruction of lesion"
* SCT#87279008    "Excision of lesion"
* SCT#43075005    "Segmental colectomy"
* SCT#307656000    "Subtotal colectomy with ileosigmoid anastomosis"
* SCT#26390003    "Total  colectomy"
* SCT#174059005    "Proctocolectomy"
* SCT#82874003    "Operation on colon [NOS]"
* SCT#52838002    "Destruction of lesion"
* SCT#79764004    "Excision of lesion"
* SCT#82035006    "Resection of polyp"
* SCT#116237003    "Excision of lesion of rectum "
* SCT#307009004    "Wedge resection"
* SCT#86789002    "Abdominoperineal pull through"
* SCT#235364003    "Total Proctectomy"
* SCT#26390003    "Total  colectomy"
* SCT#174059005    "Proctocolectomy"
* SCT#118841000    "Operation on rectosigmoid [NOS]"
* SCT#52838002    "Destruction of lesion"
* SCT#79764004    "Excision of lesion"
* SCT#82035006    "Resection of polyp"
* SCT#116237003    "Excision of lesion of rectum "
* SCT#307009004    "Wedge resection"
* SCT#86789002    "Abdominoperineal pull through"
* SCT#235364003    "Total Proctectomy"
* SCT#174059005    "Proctocolectomy"
* SCT#74971002    "Operation on rectum [NOS]"
* SCT#87031008    "Destruction of lesion"
* SCT#67373001    "Excision of lesion"
* SCT#35646002    "Excision of lesion of skin"
* SCT#177302005    "Wide excision of skin lesion"
* SCT#81723002    "Amputaion"
* SCT#392011001    "Operation on skin [NOS]"
* SCT#31468007    "Destruction of lesion"
* SCT#67097003    "Partial splenectomy"
* SCT#174776001    "Total splenectomy"
* SCT#234319005    "Splenectomy"
* SCT#59300005    "Operation on spleen [NOS]"
* SCT#45189000    "Destruction of lesion"
* SCT#32327002    "Excision of lesion"
* SCT#49209004    "Subtotal gastrectomy"
* SCT#26452005    "Total gastrectomy"
* SCT#24431004    "Esophagoduodenostomy w/complete gastrectomy"
* SCT#287816003    "Radical gastrectomy"
* SCT#438338008    "Total gastrecomy w/extended lymphadencectomy "
* SCT#53442002    "Gastrectomy"
* SCT#16453004    "Operation on stomach [NOS]"
* SCT#12807004    "Destruction of lesion"
* SCT#176430002    "Excision of lesion"
* SCT#120001005    "Testis excision"
* SCT#396692006    "Radical Orchiectomy "
* SCT#236334001    "Total Orchiectomy"
* SCT#71657006    "Operation on testis [NOS]"
* SCT#20470003    "Destruction of lesion"
* SCT#171988007    "Excision of lesion"
* SCT#13619001    "Thyroidectomy"
* SCT#24443003    "Total thyroidectomy"
* SCT#30956003    "Subtotal thyroidectomy"
* SCT#15463004    "Operation on thyroid gland [NOS]"

ValueSet:       TumorMarkerTestVS
Description:    "Codes representing tests for tumor markers. This value set of LOINC codes is not comprehensive and can be extended. LOINC codes are preferred. Other vocabularies can be used only if the test of interest is not covered by LOINC. 

FHIR implementation note: At the current time, profiles for the specific LOINC tests mentioned here do not exist."
* LNC#1695-6		"5-Hydroxyindoleacetate [Mass/time] in 24 hour Urine"
* LNC#31203-3		"5-Hydroxyindoleacetate [Mass/volume] in 24 hour Urine"
* LNC#1692-3		"5-Hydroxyindoleacetate [Mass/volume] in Cerebral spinal fluid"
* LNC#1693-1		"5-Hydroxyindoleacetate [Mass/volume] in Serum or Plasma"
* LNC#1694-9		"5-Hydroxyindoleacetate [Mass/volume] in Urine"
* LNC#72820-4		"5-Hydroxyindoleacetate [Mass/volume] in Urine by Confirmatory method"
* LNC#14573-0		"5-Hydroxyindoleacetate [Moles/time] in 24 hour Urine"
* LNC#25971-3		"5-Hydroxyindoleacetate [Moles/volume] in 24 hour Urine"
* LNC#47544-2		"5-Hydroxyindoleacetate [Moles/volume] in Cerebral spinal fluid"
* LNC#74769-1		"5-Hydroxyindoleacetate [Moles/volume] in Platelet rich plasma"
* LNC#50149-4		"5-Hydroxyindoleacetate [Moles/volume] in Serum or Plasma"
* LNC#15009-4		"5-Hydroxyindoleacetate [Moles/volume] in Urine"
* LNC#12172-3		"5-Hydroxyindoleacetate [Presence] in 24 hour Urine" // no profile
* LNC#48168-9		"5-Hydroxyindoleacetate [Presence] in Urine"  // no profile
* LNC#11145-0       "5-Hydroxyindoleacetate/​Creatinine [Mass Ratio] in Urine"
* LNC#44909-0       "5-Hydroxyindoleacetate and Creatinine [Interpretation] in Urine"
* LNC#10459-6		"Alpha-1-Fetoprotein Ag [Presence] in Tissue by Immune stain"
* LNC#11207-8		"Alpha-1-Fetoprotein [Mass/volume] in Body fluid"
* LNC#1833-3		"Alpha-1-Fetoprotein [Mass/volume] in Cerebral spinal fluid"
* LNC#54348-8		"Alpha-1-Fetoprotein [Mass/volume] in Cord blood"
* LNC#49761-0		"Alpha-1-Fetoprotein [Mass/volume] in Peritoneal fluid"
* LNC#49762-8		"Alpha-1-Fetoprotein [Mass/volume] in Pleural fluid"
* LNC#1834-1		"Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma"
* LNC#83073-7		"Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma by Immunoassay"
* LNC#19173-4		"Alpha-1-Fetoprotein [Moles/volume] in Pleural fluid"
* LNC#19177-5		"Alpha-1-Fetoprotein [Moles/volume] in Serum or Plasma"
* LNC#31993-9		"Alpha-1-Fetoprotein [Presence] in Serum or Plasma"  // no profile
* LNC#44910-8		"Alpha-1-Fetoprotein [Units/volume] in Body fluid"
* LNC#59564-5		"Alpha-1-Fetoprotein [Units/volume] in Cerebral spinal fluid"
* LNC#19172-6		"Alpha-1-Fetoprotein [Units/volume] in Pleural fluid"
* LNC#19176-7		"Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma"
* LNC#83072-9		"Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma by Immunoassay"
* LNC#41274-2		"Alpha-1-Fetoprotein interpretation in Serum or Plasma"  // no profile
* LNC#49246-2		"Alpha-1-Fetoprotein interpretation in Serum or Plasma Narrative"  // no profile
* LNC#49585-3		"Alpha-1-Fetoprotein multiple of the median cutoff [Multiple of the median] in Serum or Plasma"
* LNC#53962-7		"Alpha-1-fetoprotein.tumor marker [Mass/volume] in Serum or Plasma"
* LNC#53960-1		"Alpha-1-fetoprotein.tumor marker [Moles/volume] in Serum or Plasma"
* LNC#53961-9		"Alpha-1-fetoprotein.tumor marker [Units/volume] in Serum or Plasma"
* LNC#10873-8		"Beta-2-Microglobulin [Mass/time] in 24 hour Urine"
* LNC#54356-1		"Beta-2-Microglobulin [Mass/volume] in 24 hour Urine"
* LNC#48166-3		"Beta-2-Microglobulin [Mass/volume] in Body fluid"
* LNC#1951-3		"Beta-2-Microglobulin [Mass/volume] in Cerebral spinal fluid"
* LNC#49081-3		"Beta-2-Microglobulin [Mass/volume] in Dialysis fluid"
* LNC#88711-7		"Beta-2-Microglobulin [Mass/volume] in Peritoneal dialysis fluid"
* LNC#59217-0		"Beta-2-Microglobulin [Mass/volume] in Peritoneal fluid"
* LNC#59218-8		"Beta-2-Microglobulin [Mass/volume] in Pleural fluid"
* LNC#1952-1		"Beta-2-Microglobulin [Mass/volume] in Serum or Plasma"
* LNC#87708-4		"Beta-2-Microglobulin [Mass/volume] in Serum or Plasma --post dialysis"
* LNC#83078-6		"Beta-2-Microglobulin [Mass/volume] in Serum or Plasma by Immunoassay"
* LNC#1953-9		"Beta-2-Microglobulin [Mass/volume] in Urine"
* LNC#83077-8		"Beta-2-Microglobulin [Mass/volume] in Urine by Immunoassay"
* LNC#56662-0		"Beta-2-Microglobulin [Moles/time] in 24 hour Urine"
* LNC#50824-2		"Beta-2-Microglobulin [Moles/volume] in 24 hour Urine"
* LNC#39458-5		"Beta-2-Microglobulin [Moles/volume] in Body fluid"
* LNC#32301-4		"Beta-2-Microglobulin [Moles/volume] in Cerebral spinal fluid"
* LNC#14626-6		"Beta-2-Microglobulin [Moles/volume] in Serum"
* LNC#76484-5		"Beta-2-Microglobulin [Moles/volume] in Serum or Plasma"
* LNC#32302-2		"Beta-2-Microglobulin [Moles/volume] in Urine"
* LNC#43919-0		"Beta-2-Microglobulin [Presence] in Cerebral spinal fluid"  // no profile
* LNC#43818-4		"Beta-2-Microglobulin [Presence] in Serum"  // no profile
* LNC#43819-2		"Beta-2-Microglobulin [Presence] in Urine"  /// no profile
* LNC#83076-0		"Beta-2-Microglobulin [Units/volume] in Serum or Plasma by Immunoassay"
* LNC#83079-4		"Beta-2-Microglobulin [Units/volume] in Urine by Immunoassay"
* LNC#10467-9		"Beta-2-Microglobulin amyloid Ag [Presence] in Tissue by Immune stain"   // no profile
* LNC#54355-3		"Beta-2-Microglobulin in CSF/Beta-2-Microglobulin in serum"
* LNC#56786-7		"Beta-2-Microglobulin.tumor marker [Mass/volume] in Serum"
* LNC#2006-5		"Cancer Ag 125 [Presence] in Serum or Plasma"
* LNC#48677-9		"Cancer Ag 125 [Presence] in Tissue by Immune stain"
* LNC#11210-2		"Cancer Ag 125 [Units/volume] in Body fluid"
* LNC#15156-3		"Cancer Ag 125 [Units/volume] in Body fluid by Dilution"
* LNC#50775-6		"Cancer Ag 125 [Units/volume] in Cerebral spinal fluid"
* LNC#68923-2		"Cancer Ag 125 [Units/volume] in Pericardial fluid"
* LNC#59040-6		"Cancer Ag 125 [Units/volume] in Peritoneal dialysis fluid"
* LNC#40618-1		"Cancer Ag 125 [Units/volume] in Peritoneal fluid"
* LNC#19165-0       "Cancer Ag 125 [Units/volume] in Pleural fluid"
* LNC#10334-1       "Cancer Ag 125 [Units/volume] in Serum or Plasma"
* LNC#15157-1       "Cancer Ag 125 [Units/volume] in Serum or Plasma by Dilution"
* LNC#83082-8       "Cancer Ag 125 [Units/volume] in Serum or Plasma by Immunoassay"
* LNC#2007-3        "Cancer Ag 15-3 [Presence] in Serum or Plasma"
* LNC#29153-4       "Cancer Ag 15-3 [Units/volume] in Body fluid"
* LNC#50776-4       "Cancer Ag 15-3 [Units/volume] in Cerebral spinal fluid"
* LNC#50777-2       "Cancer Ag 15-3 [Units/volume] in Pericardial fluid"
* LNC#50778-0       "Cancer Ag 15-3 [Units/volume] in Peritoneal fluid"
* LNC#19186-6       "Cancer Ag 15-3 [Units/volume] in Pleural fluid"
* LNC#6875-9        "Cancer Ag 15-3 [Units/volume] in Serum or Plasma"
* LNC#83083-6       "Cancer Ag 15-3 [Units/volume] in Serum or Plasma by Immunoassay"
* LNC#2009-9        "Cancer Ag 19-9 [Presence] in Serum or Plasma"
* LNC#26924-1       "Cancer Ag 19-9 [Units/volume] in Body fluid"
* LNC#50779-8       "Cancer Ag 19-9 [Units/volume] in Cerebral spinal fluid"
* LNC#50780-6       "Cancer Ag 19-9 [Units/volume] in Pericardial fluid"
* LNC#50781-4       "Cancer Ag 19-9 [Units/volume] in Peritoneal fluid"
* LNC#19163-5       "Cancer Ag 19-9 [Units/volume] in Pleural fluid"
* LNC#24108-3       "Cancer Ag 19-9 [Units/volume] in Serum or Plasma"
* LNC#83084-4       "Cancer Ag 19-9 [Units/volume] in Serum or Plasma by Immunoassay"
* LNC#2012-3        "Cancer Ag 27-29 [Presence] in Serum or Plasma"
* LNC#50782-2       "Cancer Ag 27-29 [Units/volume] in Cerebral spinal fluid"
* LNC#19187-4       "Cancer Ag 27-29 [Units/volume] in Pleural fluid"
* LNC#17842-6       "Cancer Ag 27-29 [Units/volume] in Serum or Plasma"
* LNC#12515-3       "Carcinoembryonic Ag [Mass/volume] in Body fluid"
* LNC#2037-0        "Carcinoembryonic Ag [Mass/volume] in Cerebral spinal fluid"
* LNC#40621-5       "Carcinoembryonic Ag [Mass/volume] in Pericardial fluid"
* LNC#40622-3       "Carcinoembryonic Ag [Mass/volume] in Peritoneal fluid"
* LNC#19169-2       "Carcinoembryonic Ag [Mass/volume] in Pleural fluid"
* LNC#2038-8        "Carcinoembryonic Ag [Mass/volume] in Semen"
* LNC#2039-6        "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma"
* LNC#83085-1       "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma by Immunoassay"
* LNC#19170-0       "Carcinoembryonic Ag [Moles/volume] in Pleural fluid"
* LNC#19167-6       "Carcinoembryonic Ag [Moles/volume] in Serum or Plasma"
* LNC#10469-5       "Carcinoembryonic Ag [Presence] in Tissue by Immune stain"
* LNC#19168-4       "Carcinoembryonic Ag [Units/volume] in Pleural fluid"
* LNC#10560-1       "Carcinoembryonic Ag [Units/volume] in Semen"
* LNC#19166-8       "Carcinoembryonic Ag [Units/volume] in Serum or Plasma"
* LNC#85337-4       "Estrogen receptor Ag [Presence] in Breast cancer specimen by Immune stain"
* LNC#40556-3       "Estrogen receptor Ag [Presence] in Tissue by Immune stain"
* LNC#16112-5       "Estrogen receptor [Interpretation] in Tissue"
* LNC#14130-9       "Estrogen receptor [Moles/mass] in Tissue"
* LNC#85310-1       "Estrogen receptor fluorescence intensity [Type] in Breast cancer specimen by Immune stain"
* LNC#10480-2       "Estrogen+Progesterone receptor Ag [Presence] in Tissue by Immune stain"
* LNC#48676-1       "HER2 [Interpretation] in Tissue"
* LNC#32996-1       "HER2 [Mass/volume] in Serum"
* LNC#42914-2       "HER2 [Mass/volume] in Serum by Immunoassay"
* LNC#85318-4       "HER2 [Presence] in Breast cancer specimen by FISH"
* LNC#85319-2       "HER2 [Presence] in Breast cancer specimen by Immune stain"
* LNC#51981-9       "HER2 [Presence] in Serum by Immunoassay"
* LNC#31150-6       "HER2 [Presence] in Tissue by FISH"
* LNC#72383-3       "HER2 [Presence] in Tissue by Immunoassay"
* LNC#72382-5       "HER2 [Units/volume] in Tissue by Immunoassay"
* LNC#18474-7       "HER2 Ag [Presence] in Tissue by Immune stain"
* LNC#49683-6       "HER2 gene copy number/Chromosome 17 copy number in Tissue by FISH"
* LNC#74860-8       "HER2 gene copy number/nucleus in Tissue by FISH"
* LNC#74885-5       "HER2 panel - Tissue by FISH"
* LNC#83054-7       "PD-L1 by clone 22C3 [Interpretation] in Tissue by Immune stain Narrative"
* LNC#83052-1       "PD-L1 by clone 22C3 [Presence] in Tissue by Immune stain"
* LNC#83056-2       "PD-L1 by clone 28-8 [Interpretation] in Tissue by Immune stain Narrative"
* LNC#83055-4       "PD-L1 by clone 28-8 [Presence] in Tissue by Immune stain"
* LNC#83057-0       "PD-L1 by clone SP142 [Presence] in Tissue by Immune stain"
* LNC#83053-9       "Cells.programmed cell death ligand 1/100 viable tumor cells in Tissue by Immune stain. (source: LOINC)"
* LNC#85339-0       "Progesterone receptor Ag [Presence] in Breast cancer specimen by Immune stain"
* LNC#40557-1       "Progesterone receptor Ag [Presence] in Tissue by Immune stain"
* LNC#16113-3       "Progesterone receptor [Interpretation] in Tissue"
* LNC#10861-3       "Progesterone receptor [Mass/mass] in Tissue"
* LNC#31207-4       "Progesterone receptor [Moles/mass] in Tissue"
* LNC#85331-7       "Progesterone receptor fluorescence intensity [Type] in Breast cancer specimen by Immune stain"
* LNC#47738-0       "Prostate specific Ag [Mass/volume] in Body fluid"
* LNC#59230-3       "Prostate specific Ag [Mass/volume] in Cerebral spinal fluid"
* LNC#59223-8       "Prostate specific Ag [Mass/volume] in Peritoneal fluid"
* LNC#59221-2       "Prostate specific Ag [Mass/volume] in Pleural fluid"
* LNC#19199-9       "Prostate specific Ag [Mass/volume] in Semen"
* LNC#2857-1        "Prostate specific Ag [Mass/volume] in Serum or Plasma"
* LNC#35741-8       "Prostate specific Ag [Mass/volume] in Serum or Plasma by Detection limit <= 0.01 ng/mL"
* LNC#83112-3       "Prostate specific Ag [Mass/volume] in Serum or Plasma by Immunoassay"
* LNC#34611-4       "Prostate specific Ag [Mass/volume] in Urine"
* LNC#19200-5       "Prostate specific Ag [Moles/volume] in Semen"
* LNC#19197-3       "Prostate specific Ag [Moles/volume] in Serum or Plasma"
* LNC#10508-0       "Prostate specific Ag [Presence] in Tissue by Immune stain"
* LNC#19198-1       "Prostate specific Ag [Units/volume] in Semen"
* LNC#19195-7       "Prostate specific Ag [Units/volume] in Serum or Plasma"
* LNC#15325-4       "Prostate specific Ag/Prostate volume calculated"
* LNC#15323-9       "Prostate specific Ag/Prostate volume calculated from height, width and length"
* LNC#15324-7       "Prostate specific Ag/Prostate volume calculated from planimetry"